Description: > 
  This is a template to deploy 2 Ec2 instances that will be a web server.
  how part of project number one of Seminario de sistemas 1 course.  
  Erick Roberto Tejaxun Xicon 201213050

Parameters:
  AIM:
    Type:  'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroupIds:
        - Fn::ImportValue:
            "SeminarioProyecto1-sg-ecs"      
      SubnetId:
        Fn::ImportValue:
          "SeminarioProyecto1-PrivateSubnet1"                
      KeyName: 'serverAzone1'
      ImageId: !Ref 'AIM'      

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroupIds:
        - Fn::ImportValue:
            "SeminarioProyecto1-sg-ecs"   
      SubnetId:
        Fn::ImportValue:
          "SeminarioProyecto1-PrivateSubnet1"              
      KeyName: 'serverAzone1'
      ImageId: !Ref 'AIM' 
   

Outputs:
  EC2Instance1:
    Description: Web Server 1
    Value: !Ref EC2Instance1
    Export:
      Name: "SeminarioProyecto1-ecs-sever1"

  EC2Instance1:
    Description: Web Server 2
    Value: !Ref EC2Instance2
    Export:
      Name: "SeminarioProyecto1-ecs-sever2"      

